export enum ENVIRONMENTS {
  DEVELOP = "DEVELOP",
  STAGING = "STAGING",
  UAT = "UAT",
  PRODUCTION = "PRODUCTION",
}
export enum TOKEN_TYPE {
  BASE = 'BASE',
  NOVA_BAM = 'NOVA_BAM',
}
export enum SYSTEM_MESSAGE {
  TOKEN_IS_INVALID = 'TOKEN_IS_INVALID',
  SUCCEED = 'SUCCEED',
  SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_EXISTED = 'USER_EXISTED',
}
export enum Role {
  BAM = 'BAM',
	TPKD = 'TPKD',
	SALE_ADMIN = 'SALE_ADMIN',
	SUPER_ADMIN = 'SUPER_ADMIN',
}
